services:
  postgres:
    image: postgres:11
    container_name: consumer-api-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=consumer-apidb
      - DB_USERNAME=deco
      - DB_PASSWORD=deco
    ports:
      - "5432:5432"

  consumer-api:
    image: consumer-api
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - DB_HOST=postgres
      - DB_NAME=consumer-apidb
      - DB_USERNAME=deco
      - DB_PASSWORD=deco
    tty: true
    stdin_open: true
    volumes:
      - .:/home/deco/consumer-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: {}
