services:
  postgres:
    image: postgres:11
    container_name: consumer-api-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=250'"
    environment:
      - POSTGRES_DB=consumer-apidb
      - DB_USERNAME=deco
      - DB_PASSWORD=deco
      - POSTGRES_INITDB_ARGS='--encoding=UTF-8 --lc-collate=UTF-8 --lc-ctype=UTF-8'

    ports:
      - "5432:5432"

  consumer-api:
    image: consumer-api
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - DB_HOST=postgres
      - DB_NAME=consumer-apidb
      - DB_USERNAME=deco
      - DB_PASSWORD=deco
      - REDIS_URL=redis://redis:6379/

    tty: true
    stdin_open: true
    volumes:
      - .:/home/deco/consumer-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "6379"

volumes:
  postgres_data: {}
  redis_data:
